# k8s/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: docmind-backend-service
  labels:
    app: docmind-backend
spec:
  selector:
    app: docmind-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort    # NodePort so minikube can expose it